import { Toaster } from "sonner";
import "./globals.css";
import { Metadata } from "next";
import NavBar from "@/components/NavBar";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

import Provider from "@/lib/Redux/Providers/Providers";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Textiles Managers",
  description: "Generated by amit pandey",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning className={cn("font-sans", geist.variable)}>
      <body className="antialiased relative h-dvh w-full" >
          <Provider>
          <Toaster position="bottom-center" richColors />
          <NavBar/>
          {children}
          </Provider>
      </body>
    </html>
  );
}
