import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "@/components/NavBar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Textiles Managers",
  description: "Generated by amit pandey",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en" suppressHydrationWarning>
      <meta name="viewport" content="width=device-width, initial-scale=1" />

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen relative`}>

        <div className="flex">

          <NavBar />
          <div className="p-3 w-full h-screen overflow-y-auto overflow-x-hidden border-red-400 border-4 ">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
